### ISSUE TITLE
Use env vars from README

### ISSUE THREAD

**Issue by mnowotka** [yougov/vr.cli#1]
Hi,

The official README mentions `VELOCIRAPTOR_USERNAME` and `VELOCIRAPTOR_PASSWORD` environment variables so I tried to use them but they were ignored. I searched the repo for `VELOCIRAPTOR_USERNAME` and I only found it in README.

Can we add support for those variables or remove last chapter from the readme (I'd vote for the former option and I'm happy to provide PR)?

**Comment by jaraco** [comment]
I recommend when developing the VR suite to clone the /yougov/velociraptor project. that will pull in the submodules, including this one. If you were to grow that tree, you would find the env vars, in vr.common.models IIRC.

**Comment by jaraco** [comment]
Also, I recommend relying on the key ring support for the password.
